### ISSUE TITLE
Add Betamax tests

### ISSUE THREAD

**Issue by twingly-mob** [twingly/twingly-search-api-java#9]

**Comment by walro** [comment]
The reason to why we don't use it now is due to https://github.com/betamaxteam/betamax/issues/175 seems like it doesn't work with our https endpoint.

**Comment by cowboygneox** [comment]
@walro I'm assuming you've tried? Have you tried with the most recent master?

**Comment by walro** [comment]
Hi @cowboygneox,

I haven't personally tried, @xSAVIKx was the one who tried (the author of the issue). We'll take a look at your pointers in https://github.com/betamaxteam/betamax/issues/175 and see if we can get things going, not sure when though.

Thanks for getting back to us!

**Comment by cowboygneox** [comment]
@walro When I revived Betamax, it was old and SSL was being a huge bitch on newer JVMs; I probably spent a whole weekend on it. However, I think it's working, and if it's not, I will get it working ASAP since it's mandatory for the library. Basically, if SSL isn't working, then no one is using the library, which means I'm also wasting my time working on it, and I hate wasting my time! :)

Let me know what you find, and feel free to reach out to me with any questions or concerns.

**Comment by twingly-mob** [comment]
@xSAVIKx do you mind trying getting Betamax working one more time? Looks like we tried to use the wrong version last time, https://github.com/betamaxteam/betamax/issues/175#issuecomment-194419509

**Comment by cowboygneox** [comment]
@twingly-mob QueryBuilder for this project, right? Not Betamax?

**Comment by dentarg** [comment]
@xSAVIKx #14 (and also #17) is now merged
